# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b8554fa751d543f8b59223574dd94b81d4b4718930b0b4c77bf96dfa70e4d343b948167dcb08de6f24377921ddc1fe9a9c976b943009cf85b845be3ecea0bb4

test:
  secret_key_base: 3caa5dd9404fbca1e433fe9c8703af9827da1ee323af085c99cb1e3f0264b6578e82d2c180efe43470cde96c8d9fd732b96d5b2cfb6f04f221a034bed99f5c0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
